[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
build = "build.rs"
description = "Soup FFI crate for Rust"
license = "MIT"
links = "soup"
name = "soup-sys"
repository = "https://github.com/antoyo/soup-sys-rs"
version = "0.3.1"

[build-dependencies]
pkg-config = "0.3.7"

[dependencies]
bitflags = "0.4"
gio-sys = { git = "https://github.com/gtk-rs/sys" }
glib-sys = { git = "https://github.com/gtk-rs/sys" }
gobject-sys = { git = "https://github.com/gtk-rs/sys" }
libc = "0.2"

[features]
v2_24 = []
v2_26 = ["v2_24"]
v2_26_3 = ["v2_26"]
v2_28 = ["v2_26_3"]
v2_30 = ["v2_28"]
v2_32 = ["v2_30"]
v2_34 = ["v2_32"]
v2_36 = ["v2_34"]
v2_38 = ["v2_36"]
v2_40 = ["v2_38"]
v2_42 = ["v2_40"]
v2_44 = ["v2_42"]
v2_46 = ["v2_44"]
v2_48 = ["v2_46"]
v2_50 = ["v2_48"]
v2_52 = ["v2_50"]
v2_54 = ["v2_52"]

[lib]
name = "soup_sys"
